export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const ON_NEW_TOOL = 'ON_NEW_TOOL';
export const ON_NEW_TOOL_SUCCESS = 'ON_NEW_TOOL_SUCCESS';

export const ON_FETCH_TOOLS_LIST = 'ON_FETCH_TOOLS_LIST';
export const ON_FETCH_TOOLS_LIST_SUCCESS = 'ON_FETCH_TOOLS_LIST_SUCCESS';

export const ADD_EMPLOYEE_BEGIN = 'ADD_EMPLOYEE_BEGIN';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';

export const FETCH_EMPLOYEES_BEGIN = 'FETCH_EMPLOYEES_BEGIN';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE';

export const FETCH_EMPLOYEES_TOOLS_BEGIN = 'FETCH_EMPLOYEES_TOOLS_BEGIN';
export const FETCH_EMPLOYEES_TOOLS_SUCCESS = 'FETCH_EMPLOYEES_TOOLS_SUCCESS';
export const FETCH_EMPLOYEES_TOOLS_FAILURE = 'FETCH_EMPLOYEES_TOOLS_FAILURE';

export const ON_DELETE_TOOL = 'ON_DELETE_TOOL';
export const ON_DELETE_TOOL_SUCCESS = 'ON_DELETE_TOOL_SUCCESS';

export const ON_DELETE_EMPLOYEE = 'ON_DELETE_EMPLOYEE';
export const ON_DELETE_EMPLOYEE_SUCCESS = 'ON_DELETE_EMPLOYEE_SUCCESS';

export const FETCH_EMPLOYEE_PROFILE_BEGIN = 'FETCH_EMPLOYEE_PROFILE_BEGIN';
export const FETCH_EMPLOYEE_PROFILE_SUCCESS = 'FETCH_EMPLOYEE_PROFILE_SUCCESS';
export const FETCH_EMPLOYEE_PROFILE_FAILURE = 'FETCH_EMPLOYEE_PROFILE_FAILURE';

export const UPDATE_EMPLOYEE_PROFILE_BEGIN = 'UPDATE_EMPLOYEE_PROFILE_BEGIN';
export const UPDATE_EMPLOYEE_PROFILE_SUCCESS = 'UPDATE_EMPLOYEE_PROFILE_SUCCESS';
export const UPDATE_EMPLOYEE_PROFILE_FAILURE = 'UPDATE_EMPLOYEE_PROFILE_FAILURE';