export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const ON_NEW_TOOL = 'ON_NEW_TOOL';
export const ON_NEW_TOOL_SUCCESS = 'ON_NEW_TOOL_SUCCESS';

export const ON_FETCH_TOOLS_LIST = 'ON_FETCH_TOOLS_LIST';
export const ON_FETCH_TOOLS_LIST_SUCCESS = 'ON_FETCH_TOOLS_LIST_SUCCESS';

export const ON_NEW_EMPLOYEE = 'ON_NEW_EMPLOYEE';
export const ON_NEW_EMPLOYEE_SUCCESS = 'ON_NEW_EMPLOYEE_SUCCESS';

export const ON_FETCH_EMPLOYEES = 'ON_FETCH_EMPLOYEES';
export const ON_FETCH_EMPLOYEES_SUCCESS = 'ON_FETCH_EMPLOYEES_SUCCESS';

export const ON_FETCH_EMPLOYEE_TOOLS_LIST = 'ON_FETCH_EMPLOYEE_TOOLS_LIST';
export const ON_FETCH_EMPLOYEE_TOOLS_LIST_SUCCESS = 'ON_FETCH_EMPLOYEE_TOOLS_LIST_SUCCESS';